### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by nadonomy** [vector-im/roadmap#2]
__Summary__
The current groups & communities implementation is fraught with usability issues and lacking in functionality. We'd like to make organising rooms into different sets of rooms simple and high value for major use cases.

__Intended Outcome__
Make organising and managing rooms work well for major use cases— rooms into personal lists, rooms for teams/projects, rooms for public communities.

**Comment by ndh-dominic** [comment]
@nadonomy Can I ask whether or not this is simply extending current implementation, or to actually significantly reimplement spaces?

**Comment by IPv777** [comment]
Hello !
What about : https://github.com/vector-im/roadmap/issues/39 ?

**Comment by slayernominee** [comment]
Can you maybe add the option to order the rooms? like discord channels and make categorys because I like how it works in discord with the category channel principle

**Comment by nadonomy** [comment]
@slayernominee best to add a feature request on the platform you use the most, for more discussion.

Spaces has shipped on every platform now, so closing this issue!
