### ISSUE TITLE
Delete rooms and spaces

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/roadmap#36]
**Is your feature request related to a problem? Please describe.**
When we want to delete a room, we can only kick everybody and get out of this room, but this have several issues:
- the name of the room can't be reused (`#myroom:homeserver.com`)
- the process is very long, and not explicit (people can believe you've kicked them)

**Describe the solution you'd like**
A "delete room/spaces" button

**Comment by nadonomy** [comment]
@PxBCPG again thanks for the submission, but I'm closing this out as per the README, please file suggestions as issues as described [there](https://github.com/vector-im/roadmap#readme).
