### ISSUE TITLE
Create public spaces for internal users

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/roadmap#37]
**Is your feature request related to a problem? Please describe.**
I want to create a space that people on my server could join but not everyone in the federation

**Describe the solution you'd like**
The checkbox: "prevent anyone from another server to join this space" as we have for rooms

**Comment by nadonomy** [comment]
Hey @PxBCPG thanks for the submission. Issues in this repo are maintained by the core team. For feature requests, please file suggestions as issues as described in the [README](https://github.com/vector-im/roadmap#readme).
