### ISSUE TITLE
Feature request : ping

### ISSUE THREAD

**Issue by PxBCPG** [vector-im/roadmap#38]
**Is your feature request related to a problem? Please describe.**
The feature request is inspired by a Wire (wire.com) functionality.

**Describe the solution you'd like**
Be able to send a ping, that have the same effect as a call (in terms of notifications), but that only wakes up somebody's device and doesn't start a call.

**Comment by turt2live** [comment]
Hello, please file this on a the relevant project as per the [README](https://github.com/vector-im/roadmap).

Thank you.

**Comment by PxBCPG** [comment]
Oh yes, sorry ^^
