### ISSUE TITLE
Spaces : user permissions inheritance

### ISSUE THREAD

**Issue by IPv777** [vector-im/roadmap#39]
**Feature requested**
User permissions which cascade from Spaces to rooms— to allow admins and moderators of Spaces to be able to manage all rooms, and ease managing your Space when you remove people from them.

**Comment by nadonomy** [comment]
@IPv777  thanks for the submission, I want this feature dearly myself!

However, issues in this repo are maintained by the core team. For feature requests, please file suggestions as issues as described in the [README](https://github.com/vector-im/roadmap#readme).
